// Strategy INFT ABI — key functions only (full ABI generated by Hardhat)
// ─────────────────────────────────────────────────────────────────────────────
import { parseAbi } from "viem";

export const STRATEGY_INFT_ABI = parseAbi([
  // Read
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function balanceOf(address owner) view returns (uint256)",
  "function tokenOfOwnerByIndex(address owner, uint256 index) view returns (uint256)",
  "function totalSupply() view returns (uint256)",
  "function strategyTypes(uint256 tokenId) view returns (uint8)",
  "function isComposite(uint256 tokenId) view returns (bool)",
  "function encryptedURIs(uint256 tokenId) view returns (string)",
  "function metadataHashes(uint256 tokenId) view returns (bytes32)",
  "function getParentTokenIds(uint256 tokenId) view returns (uint256[])",
  "function getStrategyInfo(uint256 tokenId) view returns (uint8,bool,uint256[],string,bytes32)",
  "function getApproved(uint256 tokenId) view returns (address)",
  "function isApprovedForAll(address owner, address operator) view returns (bool)",
  "function name() view returns (string)",
  "function symbol() view returns (string)",

  // Write
  "function mint(address to, uint8 strategyType, string encryptedURI, bytes32 metadataHash) payable returns (uint256)",
  "function purchaseStrategy(uint8 strategyType) payable returns (uint256)",
  "function clone(address to, uint256 tokenId, bytes sealedKey, bytes proof) returns (uint256)",
  "function merge(uint256 tokenIdA, uint256 tokenIdB, string compositeEncryptedURI, bytes32 compositeMetadataHash) returns (uint256)",
  "function secureTransfer(address from, address to, uint256 tokenId, bytes sealedKey, bytes proof)",
  "function authorizeUsage(uint256 tokenId, address executor, bytes permissions)",
  "function approve(address to, uint256 tokenId)",
  "function withdraw()",
  "function setApprovalForAll(address operator, bool approved)",

  // Events
  "event StrategyMinted(uint256 indexed tokenId, address indexed to, uint8 strategyType)",
  "event StrategyCloned(uint256 indexed originalId, uint256 indexed cloneId, address indexed to)",
  "event StrategiesMerged(uint256 indexed tokenIdA, uint256 indexed tokenIdB, uint256 indexed newTokenId)",
  "event MetadataUpdated(uint256 indexed tokenId, bytes32 newHash)",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
]);

export const MARKETPLACE_ABI = parseAbi([
  // Read
  "function listings(uint256 tokenId) view returns (uint256 tokenId, address seller, uint256 price, bool active, uint256 listedAt)",
  "function getActiveListings() view returns ((uint256 tokenId, address seller, uint256 price, bool active, uint256 listedAt)[])",
  "function activeListingCount() view returns (uint256)",
  "function platformFeePercent() view returns (uint256)",
  "function inftContract() view returns (address)",

  // Write
  "function listStrategy(uint256 tokenId, uint256 price)",
  "function delistStrategy(uint256 tokenId)",
  "function buyStrategy(uint256 tokenId, bytes sealedKey, bytes proof) payable",

  // Events
  "event Listed(uint256 indexed tokenId, address indexed seller, uint256 price)",
  "event Delisted(uint256 indexed tokenId, address indexed seller)",
  "event Sold(uint256 indexed tokenId, address indexed seller, address indexed buyer, uint256 price)",
]);

// Contract addresses — update after deployment
export const CONTRACT_ADDRESSES = {
  strategyINFT:  import.meta.env.VITE_INFT_CONTRACT_ADDRESS        || "0x91315edfB1a8dA67169bc704d33EBe364dCe0144",
  marketplace:   import.meta.env.VITE_MARKETPLACE_CONTRACT_ADDRESS  || "0xf4c8164364eE74cD93F8845f556B3BcDEB6759d7",
  oracle:        import.meta.env.VITE_ORACLE_CONTRACT_ADDRESS        || "0xe1048a8079c9614909721080419e7F3C0FE08DBB",
};
